src/main/java/exemplo/autenticacao/mngbeans/LoginBean.java
package exemplo.autenticacao.mngbeans;

import static com.sun.activation.registries.LogSupport.log;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import utfpr.faces.support.RequestBean;

@ManagedBean
@RequestScoped
public class LoginBean extends RequestBean {
    
    private String login;
    private String senha;
    private String result;
    
    public LoginBean() {
    }

    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getSenha() {
        return senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }

    public String getResult() {
        return result;
    }

    public void setResult(String result) {
        this.result = result;
    }

    public String logoutAction() {
        String action = null;
        HttpServletRequest request = getRequest();
        try {
            request.logout();
            action = "/index.xhtml?faces-redirect=true";
        } catch (ServletException e) {
            log("logoutAction", e);
        }
        return action;
    }
}

src/main/java/utfpr/faces/support/ApplicationBean.java
/*
 * EXEMPLOS
 */
package utfpr.faces.support;


/**
 * O bean de aplicação
 * @author Wilson
 */
public class ApplicationBean extends FacesBean {
}

src/main/java/utfpr/faces/support/FacesBean.java
/*
 * === CLASSES DE APOIO JSF ===
 * Este código fonte pode ser livremente copiado, modificado e distribuído,
 * desde que esta mensagem seja preservada.
 * Todo o esforço foi feito para escrever um código correto e eficiente, entretanto o
 * autor não assume qualquer responsabilidade, direta ou indireta sobre a aplicabilidade
 * e/ou adequação a um fim específico e não garante que esteja livre de erros.
 * Copyright (C) 2009 <a href="http://www.utfpr.edu.br">Universidade Tecnológica Federal do Paraná</a>
 */

package utfpr.faces.support;

import java.io.Serializable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.servlet.ServletContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

/**
 * Classe base para os beans de aplicação, sessão, request e página.
 * @version 1.0.0
 *
 * @author Wilson Horstmeyer Bogado <wilson@utfpr.edu.br>
 * <a href="http://www.utfpr.edu.br">Universidade Tecnológica Federal do Paraná</a>
 */
public class FacesBean implements Serializable {

    private static final Logger logger = Logger.getLogger(PageBean.class.getName());

    /**
     * Retorna o <code>FacesContext</code> corrente.
     * @return O <code>FacesContext</code>
     */
    public FacesContext getFacesContext() {
        return FacesContext.getCurrentInstance();
    }

    /**
     * Retorna o contexto externo de JSF.
     * @return O contexto externo
     */
    public ExternalContext getExternalContext() {
        return getFacesContext().getExternalContext();
    }
    
    /**
     * Retorna ou cria uma sessão. 
     * @param create {@code true} para cria uma nova sessão, caso não exista
     * @return A sessão, ou null, caso não exista
     */
    public HttpSession getSession(boolean create) {
        return (HttpSession) getExternalContext().getSession(create);
    }
    
    /**
     * Retorna a sessão atual ou {@code null} caso não exista.
     * @return A sessão existente ou {@code null}
     */
    public HttpSession getSession() {
        return getSession(false);
    }
    
    public HttpServletRequest getRequest() {
        return (HttpServletRequest) getExternalContext().getRequest();
    }
    
    /**
     * Retorna o contexto do servlet.
     * @return O contexto do servlet
     */
    public ServletContext getServletContext() {
        return (ServletContext) getExternalContext().getContext();
    }

    /**
     * Gera um log de informação com a mensagem especificada.
     * @param message A mensagem
     */
    public void log(String message) {
        logger.log(Level.INFO, message);
    }

    /**
     * Gera um log de erro com a mensagem e exceção especificadas.
     * @param message A mensagem
     * @param t A exceção
     */
    public void log(String message, Throwable t) {
        logger.log(Level.SEVERE, message, t);
    }
}

src/main/java/utfpr/faces/support/PageBean.java
/*
 * EXEMPLOS
 */
package utfpr.faces.support;

import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;

/**
 * Classe base dos managed beans de páginas JSF.
 * @author Wilson
 */
public class PageBean extends FacesBean {

    /**
     * Retorna um managed bean dado o seu nome
     * @return O bean de aplicação
     */
    public Object getBean(String name) {
        return getFacesContext().getApplication().evaluateExpressionGet(
            FacesContext.getCurrentInstance(), "#{" + name +  "}", Object.class);
    }

    /**
     * Gera uma mensagem de informação associada a um componente.
     * @param component O componente
     * @param message A mensagem
     */
    public void info(UIComponent component, String message) {
        getFacesContext().addMessage(component.getClientId(getFacesContext()),
            new FacesMessage(FacesMessage.SEVERITY_INFO, message, null));
    }

    /**
     * Gera uma mensagem de informação não associada a um componente.
     * @param message O <i>summary</i> da mensagem
     */
    public void info(String message) {
        getFacesContext().addMessage(null,
            new FacesMessage(FacesMessage.SEVERITY_INFO, message, null));
    }

    /**
     * Gera uma mensagem de advertência associada a um componente.
     * @param component O componente
     * @param message A mensagem
     */
    public void warn(UIComponent component, String message) {
        getFacesContext().addMessage(component.getClientId(getFacesContext()),
            new FacesMessage(FacesMessage.SEVERITY_WARN, message, null));
    }

    /**
     * Gera uma mensagem de advertência não associada a um componente.
     * @param message O <i>summary</i> da mensagem
     */
    public void warn(String message) {
        getFacesContext().addMessage(null,
            new FacesMessage(FacesMessage.SEVERITY_WARN, message, null));
    }

    /**
     * Gera uma mensagem de erro associada a um componente.
     * @param component O componente
     * @param message A mensagem
     */
    public void error(UIComponent component, String message) {
        getFacesContext().addMessage(component.getClientId(getFacesContext()),
            new FacesMessage(FacesMessage.SEVERITY_ERROR, message, null));
    }

    /**
     * Gera uma mensagem de erro não associada a um componente.
     * @param message <i>summary</i> da mensagem
     */
    public void error(String message) {
        getFacesContext().addMessage(null,
            new FacesMessage(FacesMessage.SEVERITY_ERROR, message, null));
    }
}

src/main/java/utfpr/faces/support/RequestBean.java
/*
 * === CLASSES DE APOIO JSF ===
 * Este código fonte pode ser livremente copiado, modificado e distribuído,
 * desde que esta mensagem seja preservada.
 * Todo o esforço foi feito para escrever um código correto e eficiente, entretanto o
 * autor não assume qualquer responsabilidade, direta ou indireta sobre a aplicabilidade
 * e/ou adequação a um fim específico e não garante que esteja livre de erros.
 * Copyright (C) 2009 <a href="http://www.utfpr.edu.br">Universidade Tecnológica Federal do Paraná</a>
 */

package utfpr.faces.support;

/**
 * Classe base para os beans de request.
 * @version 1.0.0
 *
 * @author Wilson Horstmeyer Bogado <wilson@dainf.ct.utfpr.edu.br>
 * <a href="http://www.utfpr.edu.br">Universidade Tecnológica Federal do Paraná</a>
 */
public class RequestBean extends PageBean {

}

src/main/java/utfpr/faces/support/SessionBean.java
/*
 * === CLASSES DE APOIO JSF ===
 * Este código fonte pode ser livremente copiado, modificado e distribuído,
 * desde que esta mensagem seja preservada.
 * Todo o esforço foi feito para escrever um código correto e eficiente, entretanto o
 * autor não assume qualquer responsabilidade, direta ou indireta sobre a aplicabilidade
 * e/ou adequação a um fim específico e não garante que esteja livre de erros.
 * Copyright (C) 2009 <a href="http://www.utfpr.edu.br">Universidade Tecnológica Federal do Paraná</a>
 */
package utfpr.faces.support;

/**
 * Classe base par o bean de sessão.
 * @version 1.0.0
 *
 * @author Wilson Horstmeyer Bogado <wilson@dainf.ct.utfpr.edu.br>
 * <a href="http://www.utfpr.edu.br">Universidade Tecnológica Federal do Paraná</a>
 */
public class SessionBean extends PageBean {
}

src/main/webapp/WEB-INF/templates/layout.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <f:view>
        <ui:insert name="metadata"/>
        <h:head>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <link rel="stylesheet" type="text/css" href="${facesContext.externalContext.requestContextPath}/xmlhttp/css/rime/rime.css"/>
            <link href="${facesContext.externalContext.requestContextPath}/css/default.css" rel="stylesheet" type="text/css" />
            <link href="${facesContext.externalContext.requestContextPath}/css/layout.css" rel="stylesheet" type="text/css" />
            <title>IF6AE - Exemplo de autentição com banco de dados1</title>
            <ui:insert name="styles"/>
            <ui:insert name="javascript"/>
        </h:head>

        <h:body>
            <table class="table_layout">
                <tr>
                    <td class="left_filler"/>
                    <td id="top">
                        <ui:insert name="top">
                            <a href="http://www.ct.utfpr.edu.br" target="_blank"><img src="${facesContext.externalContext.requestContextPath}/imagens/header.jpg" alt=""/></a>
                        </ui:insert>
                    </td>
                    <td class="right_filler"/>
                </tr>
                <tr>
                    <td class="left_filler"/>
                    <td id="content">
                        <ui:insert name="content">Content</ui:insert>
                    </td>
                    <td class="right_filler"/>
                </tr>
                <tr id="bottom">
                    <td class="left_filler"/>
                    <td>
                        <ui:insert name="bottom">
                            <div class="bottom_content">
                            </div>
                        </ui:insert>
                    </td>
                    <td class="right_filler"/>
                </tr>
            </table>
        </h:body>
    </f:view>
</html>

src/main/webapp/admin/admin.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                template="/WEB-INF/templates/layout.xhtml">

    <ui:define name="content">
        <h:form>
            <h:outputText value="Usuário: ${facesContext.externalContext.userPrincipal.name}"
                            rendered="${!empty facesContext.externalContext.userPrincipal}"/>
            <div>
                <h:outputText value="PÁGINA DO ADMINISTRADOR"/>
            </div>
            <a href="${facesContext.externalContext.requestContextPath}/index.xhtml">Voltar ao menu principal</a><br/>
            <h:commandButton value="Logout" action="#{loginBean.logoutAction}"/>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/aluno/aluno.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                template="/WEB-INF/templates/layout.xhtml">

    <ui:define name="content">
        <h:form>
            <h:outputText value="Usuário: ${facesContext.externalContext.userPrincipal.name}"
                            rendered="${!empty facesContext.externalContext.userPrincipal}"/>
            <div>
                <h:outputText value="PÁGINA DO ALUNO"/>
            </div>
            <a href="${facesContext.externalContext.requestContextPath}/index.xhtml">Voltar ao menu principal</a><br/>
            <h:commandButton value="Logout" action="#{loginBean.logoutAction}"/>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                template="/WEB-INF/templates/layout.xhtml">

    <ui:define name="content">
        <h:form>
             <h:outputText value="Usuário: ${request.userPrincipal.name}"
                             rendered="${not empty request.userPrincipal}"/>
            <div>
                <h:outputText value="PÁGINA PRINCIPAL"/>
            </div>
            <a href="${request.contextPath}/admin/admin.xhtml">Acesso do Administrador</a><br/>
            <a href="${request.contextPath}/prof/professor.xhtml">Acesso do Professor</a><br/>
            <a href="${request.contextPath}/aluno/aluno.xhtml">Acesso do Aluno</a><br/>
            <h:commandButton value="Logout" action="#{loginBean.logoutAction}" rendered="${not empty request.userPrincipal}"/>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                template="/WEB-INF/templates/layout.xhtml">

    <ui:define name="metadata">
        <f:metadata>
            <f:viewParam name="result" value="#{loginBean.result}"/>
        </f:metadata>
    </ui:define>
    
    <ui:define name="content">
        <form method="POST" action="j_security_check">
            <div style="margin: 1em 0">
                <div style="margin: 0.5em 0">
                    <label for="usuarioInput" class="iceOutLbl" style="display: inline-block; width: 58px">Usuário</label>
                    <input id="usuarioInput" class="iceInpTxt" type="text" name="j_username"/>
                </div>
                <div style="margin: 0.5em 0">
                    <label for="senhaInput" class="iceOutLbl" style="display: inline-block; width: 58px">Senha</label>
                    <input id="senhaInput" class="iceInpSecrt" type="password" name="j_password"/>
                </div>
            </div>
            <input type="submit" class="iceCmdBtn" value="Entrar" style="width: 120px"/>
        </form>
        <div style="margin: 1em 0; color: red">#{empty loginBean.result ? "" : "Acesso negado"}</div>
    </ui:define>
    
</ui:composition>

src/main/webapp/prof/professor.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                template="/WEB-INF/templates/layout.xhtml">

    <ui:define name="content">
        <h:form>
            <h:outputText value="Usuário: ${facesContext.externalContext.userPrincipal.name}"
                            rendered="${!empty facesContext.externalContext.userPrincipal}"/>
            <div>
                <h:outputText value="PÁGINA DO PROFESSOR"/>
            </div>
            <a href="${facesContext.externalContext.requestContextPath}/index.xhtml">Voltar ao menu principal</a><br/>
            <h:commandButton value="Logout" action="#{loginBean.logoutAction}"/>
        </h:form>
    </ui:define>
</ui:composition>